version: "3"

volumes:
  postgres: {}
  nginx: {}
  flask: {}

services:
  postgres:
    image: postgres:14
    container_name: postgres
    env_file: .env
    user: "${UID}:${GID}"
    ports:
      - 8001:5432
    volumes:
      - ${HOME}/postgres-data/:/var/lib/postgresql/data

  flask:
    build: .
    container_name: flask
    depends_on:
      - postgres
    env_file: .env
    volumes: [".:/app"]

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - flask
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
