"""rename relationship fields

Revision ID: 73e00540569b
Revises: f620cc0536a2
Create Date: 2022-06-24 19:54:30.533517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "73e00540569b"
down_revision = "f620cc0536a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "relationships", sa.Column("requester_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "relationships", sa.Column("addressee_id", sa.Integer(), nullable=True)
    )

    op.execute("UPDATE relationships SET requester_id = from_id")
    op.execute("UPDATE relationships SET addressee_id = to_id")

    op.alter_column(
        "relationships", sa.Column("requester_id", sa.Integer(), nullable=False)
    )
    op.alter_column(
        "relationships", sa.Column("addressee_id", sa.Integer(), nullable=False)
    )

    op.drop_index("ix_relationships_to_id", table_name="relationships")
    op.create_index(
        op.f("ix_relationships_addressee_id"),
        "relationships",
        ["addressee_id"],
        unique=False,
    )
    op.drop_constraint(
        "relationships_from_id_fkey", "relationships", type_="foreignkey"
    )
    op.create_foreign_key(None, "relationships", "users", ["requester_id"], ["id"])
    op.drop_column("relationships", "to_id")
    op.drop_column("relationships", "from_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "relationships",
        sa.Column("from_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "relationships",
        sa.Column("to_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )

    op.execute("UPDATE relationships SET from_id = requester_id")
    op.execute("UPDATE relationships SET to_id = addressee_id")

    op.alter_column("relationships", sa.Column("from_id", sa.Integer(), nullable=False))
    op.alter_column("relationships", sa.Column("to_id", sa.Integer(), nullable=False))

    op.drop_constraint(None, "relationships", type_="foreignkey")
    op.create_foreign_key(
        "relationships_from_id_fkey", "relationships", "users", ["from_id"], ["id"]
    )
    op.drop_index(op.f("ix_relationships_addressee_id"), table_name="relationships")
    op.create_index("ix_relationships_to_id", "relationships", ["to_id"], unique=False)
    op.drop_column("relationships", "addressee_id")
    op.drop_column("relationships", "requester_id")
    # ### end Alembic commands ###
