"""Add relationship table

Revision ID: b7b2bf5adf05
Revises: 
Create Date: 2022-06-12 17:09:24.658829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b7b2bf5adf05"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "relationships",
        sa.Column("from_id", sa.Integer(), nullable=False),
        sa.Column("to_id", sa.Integer(), nullable=False),
        sa.Column(
            "relationship_type",
            sa.Enum("FRIEND", "BLOCK", name="relationshiptype"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("from_id", "to_id"),
    )
    op.create_index(
        op.f("ix_relationships_to_id"), "relationships", ["to_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_relationships_to_id"), table_name="relationships")
    op.drop_table("relationships")
    # ### end Alembic commands ###
