"""Add user ts_vector

Revision ID: f620cc0536a2
Revises: b7b2bf5adf05
Create Date: 2022-06-14 21:46:06.265267

"""
from alembic import op
import sqlalchemy as sa
from app.models.ts_vector import TSVector


# revision identifiers, used by Alembic.
revision = "f620cc0536a2"
down_revision = "b7b2bf5adf05"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "__ts_vector__",
            TSVector(),
            sa.Computed(
                "to_tsvector('english', name || ' ' || username)", persisted=True
            ),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_user___ts_vector__",
        "users",
        ["__ts_vector__"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user___ts_vector__", table_name="users", postgresql_using="gin")
    op.drop_column("users", "__ts_vector__")
    # ### end Alembic commands ###
