"""conversations cleared at

Revision ID: a2e0463abe2d
Revises: 6441f6a4ee7c
Create Date: 2022-12-21 10:43:41.892045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e0463abe2d'
down_revision = '6441f6a4ee7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('sender_cleared_at', sa.DateTime(), nullable=True))
    op.add_column('conversations', sa.Column('recipient_cleared_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'recipient_cleared_at')
    op.drop_column('conversations', 'sender_cleared_at')
    # ### end Alembic commands ###
